apiVersion: v1
kind: PersistentVolume
metadata:
 name: pg-pv
 labels:
    app: postgres
spec:
 capacity:
   storage: 3Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Delete
 awsElasticBlockStore:
   volumeID: vol-001c4f58313e38a45
   fsType: ext4