apiVersion: apps/v1
kind: Deployment
metadata:
 name: react-frontend
spec:
 replicas: 1
 selector:
      matchLabels:
        app: react
 template:
   metadata:
      labels:
        app: react
   spec:
     containers:
     - name: frontend
       image: poultryghast/react_frontend
       imagePullPolicy: IfNotPresent
       ports:
         - containerPort: 80